HKG: Car Port for Genesis GV70 Electrified 2023 (HDA2)
commaai/opendbc pull request #1131
Opened 2024-08-20 13:54 UTC by sunnyhaibin

**Checklist**

- [x] added entry to CAR in selfdrive/car/*/values.py and ran `selfdrive/car/docs.py` to generate new docs
- [x] test route added to [routes.py](https://github.com/commaai/openpilot/blob/master/selfdrive/car/tests/routes.py)
- [x] route with openpilot: `afe09b9f5d3f3548/00000011--15fefe1c50`
- [x] route with openpilot longitudinal: `afe09b9f5d3f3548/0000001b--a1129a4a15` 
- [x] route with stock system: `afe09b9f5d3f3548/00000005--fe8cd35e57`
- [x] car harness used (if comma doesn't sell it, put N/A): `Harness Q`

Thanks to community 2023 Genesis GV70 Electrified (HDA2) owner gv70e_81046 (Discord).

Superseded https://github.com/commaai/openpilot/pull/32765

2024-09-24 00:45 UTC, jyoung8607 commented
Looks like the ACCELERATOR message is common to all CAN-FD EVs. Does it only have gearshift position data on this car, or might it be available on all the others? Might be an opportunity here to reduce complexity rather than increase it.

Also:

> - [x] test route added to [routes.py](https://github.com/commaai/openpilot/blob/master/selfdrive/car/tests/routes.py)

This is not done, will need you to add it.

2024-09-24 03:08 UTC, Net1Pro commented
Hello,

Please forgive my ignorance but I am not sure if the " This is not done,
will need you to add it" (uploading test route) was directed to me or
someone else.
Please advise.
Thanks!


On Mon, Sep 23, 2024 at 8:45 PM Jason Young ***@***.***>
wrote:

> Looks like the ACCELERATOR message is common to all CAN-FD EVs. Does it
> only have gearshift position data on this car, or might it be available on
> all the others? Might be an opportunity here to reduce complexity rather
> than increase it.
>
> Also:
>
>
>    - test route added to routes.py
>    <https://github.com/commaai/openpilot/blob/master/selfdrive/car/tests/routes.py>
>
> This is not done, will need you to add it.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/commaai/opendbc/pull/1131#issuecomment-2369873991>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BIZXN2SPXTF6DTVGMVG3IKDZYCY2JAVCNFSM6AAAAABMZ66NBWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNRZHA3TGOJZGE>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2024-09-24 04:00 UTC, sunnyhaibin commented
> Looks like the ACCELERATOR message is common to all CAN-FD EVs. Does it only have gearshift position data on this car, or might it be available on all the others? Might be an opportunity here to reduce complexity rather than increase it.

The signals in the `ACCELERATOR` message are only relevant for CAN-FD EV platforms, and for this car, the gearshift position data is not found in `GEAR_ALT` or `GEAR_ALT_2`. It's one of the unique quirks of HKG CAN-FD across different models and model years.

> * [x]  test route added to [routes.py](https://github.com/commaai/openpilot/blob/master/selfdrive/car/tests/routes.py)
> 
> This is not done, will need you to add it.

Added back!

2024-09-24 23:37 UTC, jyoung8607 commented
Going to mark this as draft, pending a slight refactor to cleanly support all CAN-FD EV vehicles the same way.

2024-09-26 17:53 UTC, jyoung8607 requested changes

2024-09-26 17:53 UTC, jyoung8607 commented on opendbc/car/hyundai/values.py
> +  # https://www.genesis.com/content/dam/genesis-p2/au/assets/models/electrified-gv70/specs/Genesis_GV70_EV_August_2022_v0.1.pdf
```suggestion
```

2024-09-26 17:53 UTC, jyoung8607 commented on opendbc/car/hyundai/values.py
> +    CarSpecs(mass=2295, wheelbase=2.87, steerRatio=13.27),
Adjusting steerRatio to online learned value, slight tweak to mass per spec from Edmunds.

```suggestion
    CarSpecs(mass=2260, wheelbase=2.87, steerRatio=17.1),
```

![image](https://github.com/user-attachments/assets/13d2802a-66be-4b01-b9e1-1120e78bb924)

2024-09-26 17:53 UTC, jyoung8607 commented on opendbc/car/torque_data/override.toml
> +"GENESIS_GV70_ELECTRIFIED_1ST_GEN" = [2.5, 2.5, 0.1]
Adjusting lateral accel control parameters to match online learned performance.

```suggestion
"GENESIS_GV70_ELECTRIFIED_1ST_GEN" = [1.9, 1.9, 0.09]
```

![image](https://github.com/user-attachments/assets/5e9ae85f-02e8-46f9-9cdd-b59a793c493f)

2024-09-26 18:27 UTC, jyoung8607 commented
GTM!

* Safety and openpilot operation equivalent to all the other HKG CAN-FD EVs
* Lateral accel control performance is reasonable and meets guidelines
* No complaints of the common HKG issue with HUD grasp-wheel/take-over alerts

Offline validation:

* Test routes were already uploaded
* `pytest opendbc` passes
* `pytest selfdrive/car/tests` passes

Caveats:

* We're not seeing the VIN, but we're also not getting it from the comma fleet EV6

2024-09-26 18:27 UTC, merged