HKG: Car Port for Hyundai Palisade and Kia Telluride 2023-24 (non-HDA2)
commaai/opendbc pull request #1273
Opened 2024-09-24 20:30 UTC by sunnyhaibin

**Supersedes**
- https://github.com/commaai/openpilot/pull/27478

**Requires**
- https://github.com/commaai/panda/pull/1267
- https://github.com/commaai/opendbc/pull/1269
- https://github.com/commaai/openpilot/pull/29695
- https://github.com/commaai/openpilot/pull/29733

2024-09-29 16:48 UTC, jyoung8607 requested changes
I think this one could use some preparatory refactors before going forward.

* The CanBus class should move from hyundaicanfd to values, and then just switch to always using that for bus selection on all cars, getting rid of a lot of extra conditional branches.
* The CAN packer functions should gain a bus argument and the bus should be passed down from carcontroller. This will allow a lot of cleanup, especially the duplicate lkas11 packer.

I can help with some of the refactors later.

2024-09-29 16:48 UTC, jyoung8607 commented on opendbc/car/hyundai/carstate.py
> +      scc_bus = "SCC12" if self.CP.flags & HyundaiFlags.CAN_CANFD_HYBRID else "SCC11"
scc_bus is a misnomer, it's really scc_msg.

2024-11-28 07:31 UTC, Falseclock commented
@sunnyhaibin 

Installed [openpilot palisade-2023-port-1](https://github.com/sunnypilot/sunnypilot/tree/palisade-2023-port-1)

via SSH downloaded this branch, built and installed.

copied buld into /data/openpilot/opendbc_new directory
and pointed symlink /data/openpilot/opendbc to the new one.

Logs available under this route
1c5bce9ae79fdd50/00000002--2668ae0c6e

installation and build log
`
comma@comma-e6eba35d:~/opendbc$
Using username "comma".
Authenticating with public key "aws.mp.kz"
                      .~ssos+.
                    +8888888888i,
                   {888888888888o.
                   h8888888888888k
                   t888888888s888k
                    `t88888d/ h88k
                       ```    h88l
                             ,88k`
                            .d8h`
                           +d8h
                        _+d8h`
                      ;y8h+`
                      |-`


Welcome to AGNOS (GNU/Linux 4.9.103+ aarch64)

Here are some useful commands:
  Enter the tmux session where the comma service runs
  (note: tmux prefix key has been configured to backtick)
    └── tmux a

  Install Ubuntu packages
    └── sudo apt update && sudo apt install <pkg>

  Install Python packages
    └── pip install <pkg>

When modifying AGNOS, keep in mind that the system partition isn't
particularly large. /data/ is the largest partition, and unlike the
rest of the partitions, it will persist across AGNOS updates.

Want a clean slate? Reflash AGNOS with https://flash.comma.ai.


The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

comma@comma-e6eba35d:/data/openpilot$ cd ~
comma@comma-e6eba35d:~$ pws
-bash: pws: command not found
comma@comma-e6eba35d:~$ pwd
/home/comma
comma@comma-e6eba35d:~$ ls
comma@comma-e6eba35d:~$
comma@comma-e6eba35d:~$
comma@comma-e6eba35d:~$ sudo apt-get update
Get:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease [265 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease [128 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease [128 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease [128 kB]
Get:5 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 Packages [940 kB]
Get:6 http://ports.ubuntu.com/ubuntu-ports focal/main Translation-en [506 kB]
Get:7 http://ports.ubuntu.com/ubuntu-ports focal/restricted arm64 Packages [1,300 B]
Get:8 http://ports.ubuntu.com/ubuntu-ports focal/restricted Translation-en [6,212 B]
Get:9 http://ports.ubuntu.com/ubuntu-ports focal/universe arm64 Packages [8,458 kB]
Get:10 http://ports.ubuntu.com/ubuntu-ports focal/universe Translation-en [5,124 kB]
Get:11 http://ports.ubuntu.com/ubuntu-ports focal/multiverse arm64 Packages [114 kB]
Get:12 http://ports.ubuntu.com/ubuntu-ports focal/multiverse Translation-en [104 kB]
Get:13 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 Packages [2,857 kB]
Get:14 http://ports.ubuntu.com/ubuntu-ports focal-updates/main Translation-en [564 kB]
Get:15 http://ports.ubuntu.com/ubuntu-ports focal-updates/restricted arm64 Packages [47.6 kB]
Get:16 http://ports.ubuntu.com/ubuntu-ports focal-updates/restricted Translation-en [473 kB]
Get:17 http://ports.ubuntu.com/ubuntu-ports focal-updates/universe arm64 Packages [1,161 kB]
Get:18 http://ports.ubuntu.com/ubuntu-ports focal-updates/universe Translation-en [297 kB]
Get:19 http://ports.ubuntu.com/ubuntu-ports focal-updates/multiverse arm64 Packages [10.7 kB]
Get:20 http://ports.ubuntu.com/ubuntu-ports focal-updates/multiverse Translation-en [7,936 B]
Get:21 http://ports.ubuntu.com/ubuntu-ports focal-backports/main arm64 Packages [45.4 kB]
Get:22 http://ports.ubuntu.com/ubuntu-ports focal-backports/main Translation-en [16.3 kB]
Get:23 http://ports.ubuntu.com/ubuntu-ports focal-backports/universe arm64 Packages [24.3 kB]
Get:24 http://ports.ubuntu.com/ubuntu-ports focal-backports/universe Translation-en [16.3 kB]
Get:25 http://ports.ubuntu.com/ubuntu-ports focal-security/main arm64 Packages [2,534 kB]
Get:26 http://ports.ubuntu.com/ubuntu-ports focal-security/main Translation-en [484 kB]
Get:27 http://ports.ubuntu.com/ubuntu-ports focal-security/restricted arm64 Packages [47.3 kB]
Get:28 http://ports.ubuntu.com/ubuntu-ports focal-security/restricted Translation-en [456 kB]
Get:29 http://ports.ubuntu.com/ubuntu-ports focal-security/universe arm64 Packages [939 kB]
Get:30 http://ports.ubuntu.com/ubuntu-ports focal-security/universe Translation-en [215 kB]
Get:31 http://ports.ubuntu.com/ubuntu-ports focal-security/multiverse arm64 Packages [5,392 B]
Get:32 http://ports.ubuntu.com/ubuntu-ports focal-security/multiverse Translation-en [5,968 B]
Fetched 26.1 MB in 12s (2,179 kB/s)
Reading package lists... Done
comma@comma-e6eba35d:~$ sudo apt-get install -y git python3-pip
Reading package lists... Done
Building dependency tree... Done
The following additional packages will be installed:
  python-pip-whl
Suggested packages:
  git-daemon-run | git-daemon-sysvinit git-doc git-el git-email git-gui gitk gitweb git-cvs git-mediawiki git-svn
Recommended packages:
  python3-dev
The following packages will be upgraded:
  git python-pip-whl python3-pip
3 upgraded, 0 newly installed, 0 to remove and 139 not upgraded.
Need to get 6,466 kB of archives.
After this operation, 11.3 kB disk space will be freed.
Get:1 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 git arm64 1:2.25.1-1ubuntu3.13 [4,427 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports focal-updates/universe arm64 python3-pip all 20.0.2-5ubuntu1.11 [231 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports focal-updates/universe arm64 python-pip-whl all 20.0.2-5ubuntu1.11 [1,808 kB]
Fetched 6,466 kB in 3s (2,423 kB/s)
(Reading database ... 92839 files and directories currently installed.)
Preparing to unpack .../git_1%3a2.25.1-1ubuntu3.13_arm64.deb ...
Unpacking git (1:2.25.1-1ubuntu3.13) over (1:2.25.1-1ubuntu3.11) ...
Preparing to unpack .../python3-pip_20.0.2-5ubuntu1.11_all.deb ...
Unpacking python3-pip (20.0.2-5ubuntu1.11) over (20.0.2-5ubuntu1.10) ...
Preparing to unpack .../python-pip-whl_20.0.2-5ubuntu1.11_all.deb ...
Unpacking python-pip-whl (20.0.2-5ubuntu1.11) over (20.0.2-5ubuntu1.10) ...
Setting up git (1:2.25.1-1ubuntu3.13) ...
Setting up python-pip-whl (20.0.2-5ubuntu1.11) ...
Setting up python3-pip (20.0.2-5ubuntu1.11) ...
Processing triggers for man-db (2.9.1-1) ...
Not building database; man-db/auto-update is not 'true'.
comma@comma-e6eba35d:~$ pip uninstall opendbc
WARNING: Skipping opendbc as it is not installed.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
comma@comma-e6eba35d:~$ git clone https://github.com/sunnypilot/opendbc
Cloning into 'opendbc'...
remote: Enumerating objects: 12400, done.
remote: Counting objects: 100% (3928/3928), done.
remote: Compressing objects: 100% (565/565), done.
remote: Total 12400 (delta 3622), reused 3530 (delta 3361), pack-reused 8472 (from 1)
Receiving objects: 100% (12400/12400), 4.24 MiB | 745.00 KiB/s, done.
Resolving deltas: 100% (9273/9273), done.
comma@comma-e6eba35d:~$ cd opendbc/
comma@comma-e6eba35d:~/opendbc$ git switch palisade-2023-port-2-new
Branch 'palisade-2023-port-2-new' set up to track remote branch 'palisade-2023-port-2-new' from 'origin'.
Switched to a new branch 'palisade-2023-port-2-new'
comma@comma-e6eba35d:~/opendbc$ pip install .
Processing /home/comma/opendbc
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pandacan@ git+https://github.com/sunnypilot/panda.git@palisade-2023-port-1
  Cloning https://github.com/sunnypilot/panda [...]

2024-11-30 21:04 UTC, Falseclock commented
@sunnyhaibin

Still have troubles to use Comma 3X with Hyundai Plaisade 2023 for non US market with R-Harness

tried different builds as well as with stock opendbc and manually compiled 

here is 
1c5bce9ae79fdd50/2024-11-30--14-16-28
1c5bce9ae79fdd50/00000001--345a7908b7
1c5bce9ae79fdd50/00000000--d2c80deae9
1c5bce9ae79fdd50/00000004--1152211887
1c5bce9ae79fdd50/00000003--b3f173e97f


Also tried to run test
```
comma@comma-e6eba35d:/data/opendbc/examples$ python3 joystick.py

Gas/brake control: `W` and `S` keys
Steering control: `A` and `D` keys
Buttons
- `R`: Resets axes
- `C`: Cancel cruise control
INFO: connecting to panda 330031000551323431333839
Getting VIN & FW versions
iso-tp query bad response: (2004, None) - 0x7f2231
Error processing UDS response: (2022, None)
Traceback (most recent call last):
  File "/data/pythonpath/opendbc/car/isotp_parallel_query.py", line 109, in get_data
    dat, rx_in_progress = msg.recv()
                          ^^^^^^^^^^
  File "/data/pythonpath/panda/python/uds.py", line 456, in recv
    frame_type = self._isotp_rx_next(msg)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pythonpath/panda/python/uds.py", line 507, in _isotp_rx_next
    assert self.rx_idx & 0xF == rx_data[0] & 0xF, "isotp - rx: invalid consecutive frame index"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: isotp - rx: invalid consecutive frame index
got vin with request=b'"\xf1\x90'
iso-tp query bad response: (1969, None) - 0x7f2231
Error processing UDS response: (2000, None)
Traceback (most recent call last):
  File "/data/pythonpath/opendbc/car/isotp_parallel_query.py", line 109, in get_data
    dat, rx_in_progress = msg.recv()
                          ^^^^^^^^^^
  File "/data/pythonpath/panda/python/uds.py", line 456, in recv
    frame_type = self._isotp_rx_next(msg)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pythonpath/panda/python/uds.py", line 507, in _isotp_rx_next
    assert self.rx_idx & 0xF == rx_data[0] & 0xF, "isotp - rx: invalid consecutive frame index"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: isotp - rx: invalid consecutive frame index
Error processing UDS response: (2000, None)
Traceback (most recent call last):
  File "/data/pythonpath/opendbc/car/isotp_parallel_query.py", line 109, in get_data
    dat, rx_in_progress = msg.recv()
                          ^^^^^^^^^^
  File "/data/pythonpath/panda/python/uds.py", line 456, in recv
    frame_type = self._isotp_rx_next(msg)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pythonpath/panda/python/uds.py", line 507, in _isotp_rx_next
    assert self.rx_idx & 0xF == rx_data[0] & 0xF, "isotp - rx: invalid consecutive frame index"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: isotp - rx: invalid consecutive frame index
Error processing UDS response: (2000, None)
Traceback (most recent call last):
  File "/data/pythonpath/opendbc/car/isotp_parallel_query.py", line 109, in get_data
    dat, rx_in_progress = msg.recv()
                          ^^^^^^^^^^
  File "/data/pythonpath/panda/python/uds.py", line 456, in recv
    frame_type = self._isotp_rx_next(msg)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pythonpath/panda/python/uds.py", line 507, in _isotp_rx_next
    assert self.rx_idx & 0xF == rx_data[0] & 0xF, "isotp - rx: invalid consecutive frame index"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: isotp - rx: invalid consecutive frame index
Error processing UDS response: (2000, None)
Traceback (most recent call last):
  File "/data/pythonpath/opendbc/car/isotp_parallel_query.py", line 109, in get_data
    dat, rx_in_progress = msg.recv()
                          ^^^^^^^^^^
  File "/data/pythonpath/panda/python/uds.py", line 456, in recv
    frame_type = self._isotp_rx_next(msg)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pythonpath/panda/python/uds.py", line 507, in _isotp_rx_next
    assert self.rx_idx & 0xF == rx_data[0] & 0xF, "isotp - rx: invalid consecutive frame index"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: isotp - rx: invalid consecutive frame index
iso-tp query timeout while receiving response: (1975, None)
iso-tp query timeout while receiving response: (1988, None)
iso-tp query bad response: (1969, None) - 0x7f2231
Error processing UDS response: (1988, None)
Traceback (most recent call last):
  File "/data/pythonpath/opendbc/car/isotp_parallel_query.py", line 109, in get_data
    dat, rx_in_progress = msg.recv()
                          ^^^^^^^^^^
  File "/data/pythonpath/panda/python/uds.py", line 456, in recv
    frame_type = self._isotp_rx_next(msg)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pythonpath/panda/python/uds.py", line 507, in _isotp_rx_next
    assert self.rx_idx & 0xF == rx_data[0] & 0xF, "isotp - rx: invalid consecutive frame index"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: isotp - rx: invalid consecutive frame index
Error processing UDS response: (1975, None)
Traceback (most recent call last):
  File "/data/pythonpath/opendbc/car/isotp_parallel_query.py", line 109, in get_data
    dat, rx_in_progress = msg.recv()
                          ^^^^^^^^^^
  File "/data/pythonpath/panda/python/uds.py", line 456, in recv
    frame_type = self._isotp_rx_next(msg)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pythonpath/panda/python/uds.py", line 507, in _isotp_rx_next
    assert self.rx_idx & 0xF == rx_data[0] & 0xF, "isotp - rx: invalid consecutive frame index"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: isotp - rx: invalid consecutive frame index
Error processing UDS response: (2004, None)
Traceback (most recent call last):
  File "/data/pythonpath/opendbc/car/isotp_parallel_query.py", line 109, in get_data
    dat, rx_in_progress = msg.recv()
                          ^^^^^^^^^^
  File "/data/pythonpath/panda/python/uds.py", line 456, in recv
    frame_type = self._isotp_rx_next(msg)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pythonpath/panda/python/uds.py", line 507, in _isotp_rx_next
    assert self.rx_idx & 0xF == rx_data[0] & 0xF, "isotp - rx: invalid consecutive frame index"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: isotp - rx: invalid consecutive frame index
Error processing UDS response: (2004, None)
Traceback (most recent call last):
  File "/data/pythonpath/opendbc/car/isotp_parallel_query.py", line 109, in get_data
    dat, rx_in_progress = msg.recv()
                          ^^^^^^^^^^
  File "/data/pythonpath/panda/python/uds.py", line 456, in recv
    frame_type = self._isotp_rx_next(msg)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pythonpath/panda/python/uds.py", line 507, in _isotp_rx_next
    assert self.rx_idx & 0xF == rx_data[0] & 0xF, "isotp - rx: invalid consecutive frame index"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: isotp - rx: invalid consecutive frame index
Error processing UDS response: (1988, None)
Traceback (most recent call last):
  File "/data/pythonpath/opendbc/car/isotp_parallel_query.py", line 109, in get_data
    dat, rx_in_progress = msg.recv()
                          ^^^^^^^^^^
  File "/data/pythonpath/panda/python/uds.py", line 456, in recv
    frame_type = self._isotp_rx_next(msg)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pythonpath/panda/python/uds.py", line 507, in _isotp_rx_next
    assert self.rx_idx & 0xF == rx_data[0] & 0xF, "isotp - rx: invalid consecutive frame index"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: isotp - rx: invalid consecutive frame index
Error processing UDS response: (1975, None)
Traceback (most recent call last):
  File "/data/pythonpath/opendbc/car/isotp_parallel_query.py", line 109, in get_data
    dat, rx_in_progress = msg.recv()
                          ^^^^^^^^^^
  File "/data/pythonpath/panda/python/uds.py", line 456, in recv
    frame_type = self._isotp_rx_ne [...]

2024-12-05 18:35 UTC, Falseclock commented
```
*** Results for address 0x7D0 ***


0xF187 VEHICLE_MANUFACTURER_SPARE_PART_NUMBER: b'99110S8150'
0xF18B ECU_MANUFACTURING_DATE: b' "\x10\x11'
0xF18C ECU_SERIAL_NUMBER: b'\x02\x02J\x01\x01CM\x02\x03\x06\x07'
0xF191 VEHICLE_MANUFACTURER_ECU_HARDWARE_NUMBER: b'1.00'
0xF193 SYSTEM_SUPPLIER_ECU_HARDWARE_VERSION_NUMBER: b'1.00'


*** Results for address 0x7D1 ***


0xF187 VEHICLE_MANUFACTURER_SPARE_PART_NUMBER: b'58910-S8700'
0xF18B ECU_MANUFACTURING_DATE: b' "\t!'
0xF18C ECU_SERIAL_NUMBER: b'"\t!\x90uD\x15'
0xF191 VEHICLE_MANUFACTURER_ECU_HARDWARE_NUMBER: b'58910-S8700'
0xF193 SYSTEM_SUPPLIER_ECU_HARDWARE_VERSION_NUMBER: b'1.02'
0xF195 SYSTEM_SUPPLIER_ECU_SOFTWARE_VERSION_NUMBER: b'LX2010101010101"\x07\x15'

*** Results for address 0x7D4 ***


0xF187 VEHICLE_MANUFACTURER_SPARE_PART_NUMBER: b'56310-S8620'
0xF18B ECU_MANUFACTURING_DATE: b' "\x10\x13'
0xF18C ECU_SERIAL_NUMBER: b'221013CQA12209290548\x00\x00'


*** Results for address 0x7C4 ***


0xF187 VEHICLE_MANUFACTURER_SPARE_PART_NUMBER: b'99211S8150'
0xF18B ECU_MANUFACTURING_DATE: b' "\x10\x12'
0xF18C ECU_SERIAL_NUMBER: b'221012M021457'
0xF191 VEHICLE_MANUFACTURER_ECU_HARDWARE_NUMBER: b'1.00'
0xF193 SYSTEM_SUPPLIER_ECU_HARDWARE_VERSION_NUMBER: b'1.00'


```

2024-12-07 15:06 UTC, Falseclock commented
1c5bce9ae79fdd50/00000001--8051776a29

tried to add fingerprints


`      b'\xf1\x00LX2 MFC  AT RUS LHD 1.00 1.04 99211-S8150 220622',`
and


`      b'\xf1\x00LX2_ SCC F-CUP      1.00 1.01 99110-S8150         ',`

but no success

2025-02-23 10:24 UTC, ccdunder commented on opendbc/car/hyundai/interface.py
> +      if 0x485 in fingerprint[CAN.CAM]:
took a look at the test failure you mentioned and it looks like safety allows this only on bus 0

2025-02-23 20:22 UTC, sunnyhaibin commented on opendbc/car/hyundai/carstate.py
> +      scc_bus = "SCC12" if self.CP.flags & HyundaiFlags.CAN_CANFD_HYBRID else "SCC11"
@jyoung8607 fixed here: https://github.com/sunnypilot/opendbc/commit/1a7b679502d5d2178e32f0161a39544f496aef04

2025-02-24 03:11 UTC, sshane commented on opendbc/car/hyundai/values.py
> +      self.STEER_DELTA_DOWN = 3
```suggestion
      self.STEER_MAX = 270  # CAN FD max steer
      self.STEER_DRIVER_ALLOWANCE = 50  # CAN driver torque signal scaling
      self.STEER_THRESHOLD = 150  # CAN driver torque signal scaling
      self.STEER_DELTA_UP = 3  # CAN rate limits
      self.STEER_DELTA_DOWN = 7  # CAN rate limits
```
ugh

2025-02-24 03:13 UTC, sshane commented
Route where we actuated high torque: https://connect.comma.ai/e77d1aee93a898d6/00000004--7cb0b16e2d

2025-02-25 06:38 UTC, sunnyhaibin commented
This port is ready to merge, but will be placed behind the `dashcamOnly` flag until injection testing is completed by the comma team or the community.

2025-02-26 00:15 UTC, sshane commented on opendbc/car/hyundai/values.py
> +  fuzzy_platform_blacklist = {str(c) for c in (CANFD_CAR - CAN_CANFD_BLENDED_CAR - EV_CAR - CANFD_FUZZY_WHITELIST)}
why?

2025-02-26 00:15 UTC, sshane commented on opendbc/car/hyundai/values.py
> +CAN_CANFD_BLENDED_CAR = CAR.with_flags(HyundaiFlags.CAN_CANFD_BLENDED)
don't add any more sets, this was to reduce diff when merging config

2025-02-26 00:15 UTC, sshane commented on opendbc/car/torque_data/override.toml
> +"HYUNDAI_PALISADE_2023" = [3.0, 3.0, 0.1]
TODO: update from torque params with 270

2025-02-26 00:15 UTC, sshane commented on opendbc/safety/safety/safety_hyundai.h
> +  .driver_torque_allowance = (drv_trq_allowance), \
i thought this was CAN, so 50?

2025-02-26 00:15 UTC, sshane commented on opendbc/car/hyundai/values.py
> +
we should make classes/constants for the duplicate values, ideally we just define it has CAN FD steering torque, but CAN driver torque

2025-02-26 00:15 UTC, sshane commented on opendbc/car/hyundai/tests/test_hyundai.py
> +                                    CAR.GENESIS_G80, CAR.HYUNDAI_ELANTRA, CAR.HYUNDAI_PALISADE_2023}
think we do get eps, TODO: remove

2025-02-26 00:15 UTC, sshane commented on opendbc/car/hyundai/fingerprints.py
> +  },
TODO: only the telluridee we tested, then we can add new FP as we do some standard torque checks, etc.

2025-02-26 01:40 UTC, sshane commented
Ran the script in https://github.com/commaai/openpilot/pull/34710:

```python
./max_lat_accel.py 8279cfddf735a11e/00000003--c599397377/r
```

![image](https://github.com/user-attachments/assets/3a957ed5-4bf2-4c80-b7a6-39574dc9fbf9)

2025-02-26 05:22 UTC, sunnyhaibin commented
@sshane do we want to merge this first? https://github.com/commaai/opendbc/pull/1853

2025-06-09 02:22 UTC, sunnyhaibin commented
@sshane can we reopen this? Not sure why it was closed.

2026-03-02 06:52 UTC, sunnyhaibin commented
@jyoung8607 @sshane can we please reopen?

2026-07-15 01:14 UTC, sunnyhaibin commented
@sshane can we reopen this?

2026-09-21 01:50 UTC, closed without merging