Add PQ Braking and ACC led control CAN messages
commaai/opendbc pull request #422
Opened 2021-09-03 17:29 UTC by CineXWorm

mMotor_Bremse used to control braking on cars that don't support ACC.
mAWV used to control ACC led in dashboard.

2021-09-04 16:04 UTC, grekiki commented
Would help to get this merged into openpilot to be able to tune pq long with plotjuggler, seems like it doesn't take local DBCs

2021-09-06 20:03 UTC, grekiki commented
Would be really nice to have this merged for using Plotjuggler for tuning long control on PQ. Seems like plotjuggler doesn't use the local DBC(or I am just doing something wrong) @adeebshihadeh

2021-09-06 20:47 UTC, adeebshihadeh commented
LGTM. any comments @jyoung8607?

@grekiki yeah, it should use the local DBC

2021-09-06 22:45 UTC, jyoung8607 requested changes

2021-09-06 22:45 UTC, jyoung8607 commented on vw_golf_mk4.dbc
> +BO_ 644 mMotor_Bremse: 6 Motor_Diesel
```suggestion
BO_ 644 Motor_Bremse: 6 XXX
```

The prefixing `m` on message names is unique to the source of this data, we have been removing them.

2021-09-06 22:45 UTC, jyoung8607 commented on vw_golf_mk4.dbc
> +BO_ 870 mAWV: 5 ACC
```suggestion
BO_ 870 AWV: 5 XXX
```

Same as above

2021-09-06 22:45 UTC, jyoung8607 commented on vw_golf_mk4.dbc
> + SG_ MOB_Standby : 12|1@1+ (1,0) [0|1] "" Bremse_MK25AESP
[ example only ]

```suggestion
 SG_ MOB_Standby : 12|1@1+ (1,0) [0|1] ""  XXX
```

Let's lose the network-node source/consumer labels unless and until we're willing to spend the time overhauling the file to make good use of them. No real sense in adding a few PQ25-specific dangling loose references without the other DBC infrastructure for DBC editors to even make use of them. I admit to having done this inconsistently in the past but we'll clean it all up eventually.

2021-09-07 01:01 UTC, merged