VW PQ: added AWV (AEB) signals
commaai/opendbc pull request #824
Opened 2023-04-19 18:20 UTC by FLcruising

Signals useful for AEB were missing.

2023-04-21 14:25 UTC, jyoung8607 commented
You'll need to bump the message length from 5 to 8, to accommodate these newer signals.

If we're to make proper use of these later, it would help to include the VAL tables. Can you do that as well?

2023-04-21 14:34 UTC, FLcruising commented
Ah yes. Thanks for catching the message length.
Please explain what a VAL table is.

> You'll need to bump the message length from 5 to 8, to accommodate these newer signals.
> 
> If we're to make proper use of these later, it would help to include the VAL tables. Can you do that as well?

2023-04-21 14:43 UTC, jyoung8607 commented
Toward the bottom of the DBC, you'll see existing VAL entries like this:

`VAL_ 872 ACS_Sta_ADR 2 "ADR_passiv" 0 "ADR_nicht_aktiv" 1 "ADR_aktiv" 3 "irrev_Fehler" ;`

Add the corresponding ones for all the AWV signals. As an example,

`VAL_ 870 AWV_2_SU_Warnzeit 0 "frueh" 1 "normal" 2 "spaet" 3 "adaptiv" ;`

This will be useful for fields like `AWV_Text` where we may want to decode or even rewrite what's being displayed/sent. I'm pretty sure you have the data to put into these VALs, DM me if you don't.

2023-04-21 14:46 UTC, FLcruising commented
I see...they're the signal description. Yes I have them but have translated to English. Do you care?

2023-04-21 14:53 UTC, jyoung8607 commented
I prefer to keep them in their original form, at least for now. There's a valid argument to be made for translating things, but we trade off easy reconciliation with other signal names and comments, reference docs, vehicle DTCs, etc etc.

2023-04-21 14:56 UTC, FLcruising commented
Got it. Let me work on that.

2023-04-21 16:25 UTC, jyoung8607 requested changes
Since we're overhauling this whole message, can we go ahead and sort these signals by their bit offset order? `CHECKSUM` first, `ANB_CM_Anforderung` last, etc. I try to clean these up whenever I'm working on a given message.

2023-04-21 16:25 UTC, jyoung8607 commented on vw_golf_mk4.dbc
> +BO_ 870 mAWV: 8 XXX
The one thing we don't retain, from this particular data source, is the `m` prefix on message names.

```suggestion
BO_ 870 AWV: 8 XXX
```

2023-04-21 17:31 UTC, jyoung8607 approved these changes
LGTM. openpilot [doesn't currently look](https://github.com/commaai/openpilot/blob/ee15d6b1d1b2f90815d0cbf3c0f6b5adfdb0a59f/selfdrive/car/volkswagen/carstate.py#L222-L224) at the FCW/AEB signals for VW PQ, so this can be merged anytime. I'd like to do so in the future, but there will be nuances with older cars to worry about.

2023-05-20 01:19 UTC, sshane commented
Sorry for the delay, @jyoung8607 this still GTM?

2023-05-20 01:31 UTC, jyoung8607 approved these changes

2023-05-20 01:52 UTC, merged